### ISSUE TITLE
MacOS builds broken due to incorrect package format

### ISSUE THREAD

**Issue by bryan-anguiano** [jonathanabennett/megastrike#14]
**Describe the bug**
megastrike-v0.2.1_macos package broken due to incorrect format. MacOS does not recognize it and thus, cannot install. 

**To Reproduce**
1. Download package from latest release
2. Double click on package
3. See error

**Expected behavior**
should mount as a dmg file for proper installation.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 13.6.7

**Comment by bryan-anguiano** [comment]
A change was made in the GitHub actions pipeline for the MacOS build process, which broke this release from version 2.0 onward. There is no reference to a .dmg file extension.

**Comment by jonathanabennett** [comment]
Ok, let me look at this one more closely. It actually isn't supposed to be a dmg because I don't understand jPackage well enough to add the data folder to the result in a way that will let it gets installed without it being bundled into the jar file, but I may not have configured the action correctly. I will be at my MacBook late next week and I can get it working correctly again.

But what should happen is that you should be able to extract the folder, navigate to the folder, and run the `startup.sh` file. Does that work?

**Comment by bryan-anguiano** [comment]
startup.sh does not run due to incompatible architecture error.

`.openjfx/cache/19.0.2.1+1/aarch64/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))`

**Comment by bryan-anguiano** [comment]
Im using a Macbook pro with m1 Max cpu, my guess is that the application is being built for x86 and not for ARM. Your initial build process which created a .dmg worked flawlessly but like i mentioned earlier, the new process is broken for me.

**Comment by jonathanabennett** [comment]
Sorry I missed these replies earlier! But I will have access to my MacBook (which is an M1 as well) from Monday. I'll get a working artifact uploaded early next week and then try to figure out what's going on.

**Comment by jonathanabennett** [comment]
Ok, I can confirm that this is occuring as well. I suspect this is because of how JavaFX works (each OS requires its own library and the build process that doesn't produce a DMG doesn't use whatever universal versions of that exist). But I have access again to my Silicon Mac, so I will manually build a MacOS Silicon version. I have uploaded that asset to the 0.4.0 release and will continue to do this for future releases until I figure out how to do it correctly.
